theme: jekyll-theme-cayman

# 博客标题和描述
title: dxww的博客
description: dxww的博客

# 作者信息
author:
  name: dxww
  email: wenzesu@qq.com

# 博客配置
baseurl: "" # 如果使用子目录，填子目录名，如 "/blog"
url: "https://dxww123.github.io"

# 每页显示的博文数量
paginate: 5
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Markdown 设置
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

# 时区
timezone: Asia/Shanghai

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
